<?php
/**
 * FLIZpay Magento 2
 *
 * This Magento 2 extension enables to process payments with FLIZpay.
 *
 * @package FlizPay_Payment
 * @author  FLIZpay GmbH
 * @license OSL-3.0 (https://opensource.org/license/osl-3-0-php) / AFL-3.0 (https://opensource.org/license/afl-3-0-php)
 * @link    https://flizpay.de
 */

/** @var \Magento\Framework\View\Element\Template $block */
?>
<div class="flizpay-payment-failure">
    <h1><?= $block->escapeHtml(__("Payment not completed")) ?></h1>
    <p>
        <?= $block->escapeHtml(
            __(
                "Your FLIZpay payment was not completed. Your order has not been marked as paid.",
            ),
        ) ?>
    </p>
</div>
